package github.mcdatapack.more_tools_and_armor.init;

import github.mcdatapack.more_tools_and_armor.MoreToolsAndArmor;
import net.fabricmc.fabric.api.creativetab.v1.FabricCreativeModeTab;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Items;

import static github.mcdatapack.more_tools_and_armor.init.ItemInit.*;
import static github.mcdatapack.more_tools_and_armor.init.BlockInit.*;

public class ItemGroupInit {
    private static final Component MORE_TOOLS_AND_ARMOR_GROUP_TITLE = Component.translatable("itemGroup." + MoreToolsAndArmor.MOD_ID + ".more_tools_and_armor_group");
    public static final CreativeModeTab MORE_TOOLS_AND_ARMOR_GROUP = register("more_tools_and_armor_group", FabricCreativeModeTab.builder()
            .title(MORE_TOOLS_AND_ARMOR_GROUP_TITLE)
            .icon(BUDDING_AMETHYST_PICKAXE::getDefaultInstance)
            .displayItems((displayContext, entries) -> {
                entries.accept(Items.COAL);
                entries.accept(END_COAL_ORE);
                entries.accept(END_COPPER_ORE);
                entries.accept(Items.COPPER_INGOT);
                entries.accept(Items.LAPIS_LAZULI);
                entries.accept(END_LAPIS_LAZULI_ORE);
                entries.accept(END_IRON_ORE);
                entries.accept(BUDDING_AMETHYST_CRYSTAL);
                entries.accept(END_GOLD_ORE);
                entries.accept(Items.EMERALD);
                entries.accept(SCULK_EMERALD);
                entries.accept(SCULK_EMERALD_BLOCK);
                entries.accept(BLACKSTONE_EMERALD);
                entries.accept(BLACKSTONE_EMERALD_BLOCK);
                entries.accept(END_EMERALD);
                entries.accept(END_EMERALD_BLOCK);
                entries.accept(END_EMERALD_ORE);
                entries.accept(SCULK_EMERALD_ORE);
                entries.accept(BLACKSTONE_EMERALD_ORE);
                entries.accept(Items.REDSTONE);
                entries.accept(END_REDSTONE_ORE);
                entries.accept(Items.OBSIDIAN);
                entries.accept(DEEPSLATE_EMERALD_UPGRADE_SMITHING_TEMPLATE);
                entries.accept(DEEPSLATE_EMERALD);
                entries.accept(DEEPSLATE_EMERALD_BLOCK);
                entries.accept(END_DIAMOND_UPGRADE_SMITHING_TEMPLATE);
                entries.accept(END_DIAMOND_ORE);
                entries.accept(END_DIAMOND);
                entries.accept(END_DIAMOND_BLOCK);
                entries.accept(VOID_INGOT);
                entries.accept(VOID_UPGRADE_SMITHING_TEMPLATE);
                entries.accept(ONETHDENDERITE_INGOT);
                entries.accept(ONETHDENDERITE_UPGRADE_SMITHING_TEMPLATE);
                entries.accept(OLED_INGOT);
                entries.accept(OLED_UPGRADE_SMITHING_TEMPLATE);
                entries.accept(BAT_WING);
                entries.accept(ANCIENT_HONEY_BOTTLE);
                entries.accept(ANCIENT_HONEY_BLOCK);
                entries.accept(ANCIENT_COIN);
                entries.accept(ANCIENT_INGOT);
                entries.accept(ANCIENT_UPGRADE_SMITHING_TEMPLATE);

                entries.accept(OVERWORLD_UNSTABLE_ORE);
                entries.accept(NETHER_UNSTABLE_ORE);
                entries.accept(END_UNSTABLE_ORE);
                entries.accept(OVERWORLD_SHARD);
                entries.accept(NETHER_SHARD);
                entries.accept(END_SHARD);

                entries.accept(WOODEN_PAXEL);
                entries.accept(STONE_PAXEL);
                entries.accept(IRON_PAXEL);
                entries.accept(GOLDEN_PAXEL);
                entries.accept(DIAMOND_PAXEL);
                entries.accept(NETHERITE_PAXEL);
                entries.accept(COAL_PAXEL);
                entries.accept(COPPER_PAXEL);
                entries.accept(LAPIS_PAXEL);
                entries.accept(BUDDING_AMETHYST_PAXEL);
                entries.accept(REDSTONE_PAXEL);
                entries.accept(EMERALD_PAXEL);
                entries.accept(OBSIDIAN_PAXEL);
                entries.accept(DEEPSLATE_EMERALD_PAXEL);
                entries.accept(END_DIAMOND_PAXEL);
                entries.accept(VOID_PAXEL);
                entries.accept(ONETHDENDERITE_PAXEL);
                entries.accept(OLED_PAXEL);
                entries.accept(ANCIENT_PAXEL);
                entries.accept(WOODEN_HAMMER);
                entries.accept(STONE_HAMMER);
                entries.accept(IRON_HAMMER);
                entries.accept(GOLDEN_HAMMER);
                entries.accept(DIAMOND_HAMMER);
                entries.accept(NETHERITE_HAMMER);
                entries.accept(COAL_HAMMER);
                entries.accept(COPPER_HAMMER);
                entries.accept(LAPIS_HAMMER);
                entries.accept(BUDDING_AMETHYST_HAMMER);
                entries.accept(REDSTONE_HAMMER);
                entries.accept(EMERALD_HAMMER);
                entries.accept(OBSIDIAN_HAMMER);
                entries.accept(DEEPSLATE_EMERALD_HAMMER);
                entries.accept(END_DIAMOND_HAMMER);
                entries.accept(VOID_HAMMER);
                entries.accept(ONETHDENDERITE_HAMMER);
                entries.accept(OLED_HAMMER);
                entries.accept(ANCIENT_HAMMER);
                entries.accept(COAL_HELMET);
                entries.accept(COAL_CHESTPLATE);
                entries.accept(COAL_LEGGINGS);
                entries.accept(COAL_BOOTS);
                entries.accept(COAL_SWORD);
                entries.accept(COAL_AXE);
                entries.accept(COAL_PICKAXE);
                entries.accept(COAL_SHOVEL);
                entries.accept(COAL_HOE);
                entries.accept(COAL_SPEAR);
                entries.accept(BUDDING_AMETHYST_HELMET);
                entries.accept(BUDDING_AMETHYST_CHESTPLATE);
                entries.accept(BUDDING_AMETHYST_LEGGINGS);
                entries.accept(BUDDING_AMETHYST_BOOTS);
                entries.accept(BUDDING_AMETHYST_SWORD);
                entries.accept(BUDDING_AMETHYST_AXE);
                entries.accept(BUDDING_AMETHYST_PICKAXE);
                entries.accept(BUDDING_AMETHYST_SHOVEL);
                entries.accept(BUDDING_AMETHYST_HOE);
                entries.accept(BUDDING_AMETHYST_SPEAR);
                entries.accept(LAPIS_HELMET);
                entries.accept(LAPIS_CHESTPLATE);
                entries.accept(LAPIS_LEGGINGS);
                entries.accept(LAPIS_BOOTS);
                entries.accept(LAPIS_SWORD);
                entries.accept(LAPIS_AXE);
                entries.accept(LAPIS_PICKAXE);
                entries.accept(LAPIS_SHOVEL);
                entries.accept(LAPIS_HOE);
                entries.accept(LAPIS_SPEAR);
                entries.accept(EMERALD_HELMET);
                entries.accept(EMERALD_CHESTPLATE);
                entries.accept(EMERALD_LEGGINGS);
                entries.accept(EMERALD_BOOTS);
                entries.accept(EMERALD_SWORD);
                entries.accept(EMERALD_AXE);
                entries.accept(EMERALD_PICKAXE);
                entries.accept(EMERALD_SHOVEL);
                entries.accept(EMERALD_HOE);
                entries.accept(EMERALD_SPEAR);
                entries.accept(REDSTONE_HELMET);
                entries.accept(REDSTONE_CHESTPLATE);
                entries.accept(REDSTONE_LEGGINGS);
                entries.accept(REDSTONE_BOOTS);
                entries.accept(REDSTONE_SWORD);
                entries.accept(REDSTONE_AXE);
                entries.accept(REDSTONE_PICKAXE);
                entries.accept(REDSTONE_SHOVEL);
                entries.accept(REDSTONE_HOE);
                entries.accept(REDSTONE_SPEAR);
                entries.accept(OBSIDIAN_HELMET);
                entries.accept(OBSIDIAN_CHESTPLATE);
                entries.accept(OBSIDIAN_LEGGINGS);
                entries.accept(OBSIDIAN_BOOTS);
                entries.accept(OBSIDIAN_SWORD);
                entries.accept(OBSIDIAN_AXE);
                entries.accept(OBSIDIAN_PICKAXE);
                entries.accept(OBSIDIAN_SHOVEL);
                entries.accept(OBSIDIAN_HOE);
                entries.accept(OBSIDIAN_SPEAR);
                entries.accept(DEEPSLATE_EMERALD_HELMET);
                entries.accept(DEEPSLATE_EMERALD_CHESTPLATE);
                entries.accept(DEEPSLATE_EMERALD_LEGGINGS);
                entries.accept(DEEPSLATE_EMERALD_BOOTS);
                entries.accept(DEEPSLATE_EMERALD_SWORD);
                entries.accept(DEEPSLATE_EMERALD_AXE);
                entries.accept(DEEPSLATE_EMERALD_PICKAXE);
                entries.accept(DEEPSLATE_EMERALD_SHOVEL);
                entries.accept(DEEPSLATE_EMERALD_HOE);
                entries.accept(DEEPSLATE_EMERALD_SPEAR);
                entries.accept(END_DIAMOND_HELMET);
                entries.accept(END_DIAMOND_CHESTPLATE);
                entries.accept(END_DIAMOND_LEGGINGS);
                entries.accept(END_DIAMOND_BOOTS);
                entries.accept(END_DIAMOND_SWORD);
                entries.accept(END_DIAMOND_AXE);
                entries.accept(END_DIAMOND_PICKAXE);
                entries.accept(END_DIAMOND_SHOVEL);
                entries.accept(END_DIAMOND_HOE);
                entries.accept(END_DIAMOND_SPEAR);
                entries.accept(VOID_HELMET);
                entries.accept(VOID_CHESTPLATE);
                entries.accept(VOID_LEGGINGS);
                entries.accept(VOID_BOOTS);
                entries.accept(VOID_SWORD);
                entries.accept(VOID_AXE);
                entries.accept(VOID_PICKAXE);
                entries.accept(VOID_SHOVEL);
                entries.accept(VOID_HOE);
                entries.accept(VOID_SPEAR);
                entries.accept(ONETHDENDERITE_HELMET);
                entries.accept(ONETHDENDERITE_CHESTPLATE);
                entries.accept(ONETHDENDERITE_LEGGINGS);
                entries.accept(ONETHDENDERITE_BOOTS);
                entries.accept(ONETHDENDERITE_SWORD);
                entries.accept(ONETHDENDERITE_AXE);
                entries.accept(ONETHDENDERITE_PICKAXE);
                entries.accept(ONETHDENDERITE_SHOVEL);
                entries.accept(ONETHDENDERITE_HOE);
                entries.accept(ONETHDENDERITE_SPEAR);
                entries.accept(OLED_HELMET);
                entries.accept(OLED_CHESTPLATE);
                entries.accept(OLED_LEGGINGS);
                entries.accept(OLED_BOOTS);
                entries.accept(OLED_SWORD);
                entries.accept(OLED_AXE);
                entries.accept(OLED_PICKAXE);
                entries.accept(OLED_SHOVEL);
                entries.accept(OLED_HOE);
                entries.accept(OLED_SPEAR);
                entries.accept(ANCIENT_HELMET);
                entries.accept(ANCIENT_CHESTPLATE);
                entries.accept(ANCIENT_LEGGINGS);
                entries.accept(ANCIENT_BOOTS);
                entries.accept(ANCIENT_SWORD);
                entries.accept(ANCIENT_AXE);
                entries.accept(ANCIENT_PICKAXE);
                entries.accept(ANCIENT_SHOVEL);
                entries.accept(ANCIENT_HOE);
                entries.accept(ANCIENT_SPEAR);
            })
            .build());

    public static <T extends CreativeModeTab> T register(String name, T ItemGroup) {
        return Registry.register(BuiltInRegistries.CREATIVE_MODE_TAB, MoreToolsAndArmor.id(name), ItemGroup);
    }

    public static void load() {}
}
