package github.mcdatapack.more_tools_and_armor.init;

import github.mcdatapack.more_tools_and_armor.MoreToolsAndArmor;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.Items;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;

import static github.mcdatapack.more_tools_and_armor.init.ItemInit.*;
import static github.mcdatapack.more_tools_and_armor.init.BlockInit.*;

public class ItemGroupInit {
    private static final Text MORE_TOOLS_AND_ARMOR_GROUP_TITLE = Text.translatable("itemGroup." + MoreToolsAndArmor.MOD_ID + ".more_tools_and_armor_group");
    public static final ItemGroup MORE_TOOLS_AND_ARMOR_GROUP = register("more_tools_and_armor_group", FabricItemGroup.builder()
            .displayName(MORE_TOOLS_AND_ARMOR_GROUP_TITLE)
            .icon(BUDDING_AMETHYST_PICKAXE::getDefaultStack)
            .entries((displayContext, entries) -> {
                entries.add(Items.COAL);
                entries.add(END_COAL_ORE);
                entries.add(END_COPPER_ORE);
                entries.add(Items.COPPER_INGOT);
                entries.add(Items.LAPIS_LAZULI);
                entries.add(END_LAPIS_LAZULI_ORE);
                entries.add(END_IRON_ORE);
                entries.add(BUDDING_AMETHYST_CRYSTAL);
                entries.add(END_GOLD_ORE);
                entries.add(Items.EMERALD);
                entries.add(SCULK_EMERALD);
                entries.add(SCULK_EMERALD_BLOCK);
                entries.add(BLACKSTONE_EMERALD);
                entries.add(BLACKSTONE_EMERALD_BLOCK);
                entries.add(END_EMERALD);
                entries.add(END_EMERALD_BLOCK);
                entries.add(END_EMERALD_ORE);
                entries.add(SCULK_EMERALD_ORE);
                entries.add(BLACKSTONE_EMERALD_ORE);
                entries.add(Items.REDSTONE);
                entries.add(END_REDSTONE_ORE);
                entries.add(Items.OBSIDIAN);
                entries.add(DEEPSLATE_EMERALD_UPGRADE_SMITHING_TEMPLATE);
                entries.add(DEEPSLATE_EMERALD);
                entries.add(DEEPSLATE_EMERALD_BLOCK);
                entries.add(END_DIAMOND_UPGRADE_SMITHING_TEMPLATE);
                entries.add(END_DIAMOND_ORE);
                entries.add(END_DIAMOND);
                entries.add(END_DIAMOND_BLOCK);
                entries.add(VOID_INGOT);
                entries.add(VOID_UPGRADE_SMITHING_TEMPLATE);
                entries.add(ONETHDENDERITE_INGOT);
                entries.add(ONETHDENDERITE_UPGRADE_SMITHING_TEMPLATE);
                entries.add(OLED_INGOT);
                entries.add(OLED_UPGRADE_SMITHING_TEMPLATE);
                entries.add(BAT_WING);
                entries.add(ANCIENT_HONEY_BOTTLE);
                entries.add(ANCIENT_HONEY_BLOCK);
                entries.add(ANCIENT_COIN);
                entries.add(ANCIENT_INGOT);
                entries.add(ANCIENT_UPGRADE_SMITHING_TEMPLATE);

                entries.add(OVERWORLD_UNSTABLE_ORE);
                entries.add(NETHER_UNSTABLE_ORE);
                entries.add(END_UNSTABLE_ORE);
                entries.add(OVERWORLD_SHARD);
                entries.add(NETHER_SHARD);
                entries.add(END_SHARD);

                entries.add(WOODEN_PAXEL);
                entries.add(STONE_PAXEL);
                entries.add(IRON_PAXEL);
                entries.add(GOLDEN_PAXEL);
                entries.add(DIAMOND_PAXEL);
                entries.add(NETHERITE_PAXEL);
                entries.add(COAL_PAXEL);
                entries.add(COPPER_PAXEL);
                entries.add(LAPIS_PAXEL);
                entries.add(BUDDING_AMETHYST_PAXEL);
                entries.add(REDSTONE_PAXEL);
                entries.add(EMERALD_PAXEL);
                entries.add(OBSIDIAN_PAXEL);
                entries.add(DEEPSLATE_EMERALD_PAXEL);
                entries.add(END_DIAMOND_PAXEL);
                entries.add(VOID_PAXEL);
                entries.add(ONETHDENDERITE_PAXEL);
                entries.add(OLED_PAXEL);
                entries.add(ANCIENT_PAXEL);
                entries.add(WOODEN_HAMMER);
                entries.add(STONE_HAMMER);
                entries.add(IRON_HAMMER);
                entries.add(GOLDEN_HAMMER);
                entries.add(DIAMOND_HAMMER);
                entries.add(NETHERITE_HAMMER);
                entries.add(COAL_HAMMER);
                entries.add(COPPER_HAMMER);
                entries.add(LAPIS_HAMMER);
                entries.add(BUDDING_AMETHYST_HAMMER);
                entries.add(REDSTONE_HAMMER);
                entries.add(EMERALD_HAMMER);
                entries.add(OBSIDIAN_HAMMER);
                entries.add(DEEPSLATE_EMERALD_HAMMER);
                entries.add(END_DIAMOND_HAMMER);
                entries.add(VOID_HAMMER);
                entries.add(ONETHDENDERITE_HAMMER);
                entries.add(OLED_HAMMER);
                entries.add(ANCIENT_HAMMER);
                entries.add(COAL_HELMET);
                entries.add(COAL_CHESTPLATE);
                entries.add(COAL_LEGGINGS);
                entries.add(COAL_BOOTS);
                entries.add(COAL_SWORD);
                entries.add(COAL_AXE);
                entries.add(COAL_PICKAXE);
                entries.add(COAL_SHOVEL);
                entries.add(COAL_HOE);
                entries.add(BUDDING_AMETHYST_HELMET);
                entries.add(BUDDING_AMETHYST_CHESTPLATE);
                entries.add(BUDDING_AMETHYST_LEGGINGS);
                entries.add(BUDDING_AMETHYST_BOOTS);
                entries.add(BUDDING_AMETHYST_SWORD);
                entries.add(BUDDING_AMETHYST_AXE);
                entries.add(BUDDING_AMETHYST_PICKAXE);
                entries.add(BUDDING_AMETHYST_SHOVEL);
                entries.add(BUDDING_AMETHYST_HOE);
                entries.add(LAPIS_HELMET);
                entries.add(LAPIS_CHESTPLATE);
                entries.add(LAPIS_LEGGINGS);
                entries.add(LAPIS_BOOTS);
                entries.add(LAPIS_SWORD);
                entries.add(LAPIS_AXE);
                entries.add(LAPIS_PICKAXE);
                entries.add(LAPIS_SHOVEL);
                entries.add(LAPIS_HOE);
                entries.add(EMERALD_HELMET);
                entries.add(EMERALD_CHESTPLATE);
                entries.add(EMERALD_LEGGINGS);
                entries.add(EMERALD_BOOTS);
                entries.add(EMERALD_SWORD);
                entries.add(EMERALD_AXE);
                entries.add(EMERALD_PICKAXE);
                entries.add(EMERALD_SHOVEL);
                entries.add(EMERALD_HOE);
                entries.add(REDSTONE_HELMET);
                entries.add(REDSTONE_CHESTPLATE);
                entries.add(REDSTONE_LEGGINGS);
                entries.add(REDSTONE_BOOTS);
                entries.add(REDSTONE_SWORD);
                entries.add(REDSTONE_AXE);
                entries.add(REDSTONE_PICKAXE);
                entries.add(REDSTONE_SHOVEL);
                entries.add(REDSTONE_HOE);
                entries.add(OBSIDIAN_HELMET);
                entries.add(OBSIDIAN_CHESTPLATE);
                entries.add(OBSIDIAN_LEGGINGS);
                entries.add(OBSIDIAN_BOOTS);
                entries.add(OBSIDIAN_SWORD);
                entries.add(OBSIDIAN_AXE);
                entries.add(OBSIDIAN_PICKAXE);
                entries.add(OBSIDIAN_SHOVEL);
                entries.add(OBSIDIAN_HOE);
                entries.add(DEEPSLATE_EMERALD_HELMET);
                entries.add(DEEPSLATE_EMERALD_CHESTPLATE);
                entries.add(DEEPSLATE_EMERALD_LEGGINGS);
                entries.add(DEEPSLATE_EMERALD_BOOTS);
                entries.add(DEEPSLATE_EMERALD_SWORD);
                entries.add(DEEPSLATE_EMERALD_AXE);
                entries.add(DEEPSLATE_EMERALD_PICKAXE);
                entries.add(DEEPSLATE_EMERALD_SHOVEL);
                entries.add(DEEPSLATE_EMERALD_HOE);
                entries.add(END_DIAMOND_HELMET);
                entries.add(END_DIAMOND_CHESTPLATE);
                entries.add(END_DIAMOND_LEGGINGS);
                entries.add(END_DIAMOND_BOOTS);
                entries.add(END_DIAMOND_SWORD);
                entries.add(END_DIAMOND_AXE);
                entries.add(END_DIAMOND_PICKAXE);
                entries.add(END_DIAMOND_SHOVEL);
                entries.add(END_DIAMOND_HOE);
                entries.add(VOID_HELMET);
                entries.add(VOID_CHESTPLATE);
                entries.add(VOID_LEGGINGS);
                entries.add(VOID_BOOTS);
                entries.add(VOID_SWORD);
                entries.add(VOID_AXE);
                entries.add(VOID_PICKAXE);
                entries.add(VOID_SHOVEL);
                entries.add(VOID_HOE);
                entries.add(ONETHDENDERITE_HELMET);
                entries.add(ONETHDENDERITE_CHESTPLATE);
                entries.add(ONETHDENDERITE_LEGGINGS);
                entries.add(ONETHDENDERITE_BOOTS);
                entries.add(ONETHDENDERITE_SWORD);
                entries.add(ONETHDENDERITE_AXE);
                entries.add(ONETHDENDERITE_PICKAXE);
                entries.add(ONETHDENDERITE_SHOVEL);
                entries.add(ONETHDENDERITE_HOE);
                entries.add(OLED_HELMET);
                entries.add(OLED_CHESTPLATE);
                entries.add(OLED_LEGGINGS);
                entries.add(OLED_BOOTS);
                entries.add(OLED_SWORD);
                entries.add(OLED_AXE);
                entries.add(OLED_PICKAXE);
                entries.add(OLED_SHOVEL);
                entries.add(OLED_HOE);
                entries.add(ANCIENT_HELMET);
                entries.add(ANCIENT_CHESTPLATE);
                entries.add(ANCIENT_LEGGINGS);
                entries.add(ANCIENT_BOOTS);
                entries.add(ANCIENT_SWORD);
                entries.add(ANCIENT_AXE);
                entries.add(ANCIENT_PICKAXE);
                entries.add(ANCIENT_SHOVEL);
                entries.add(ANCIENT_HOE);
            })
            .build());

    public static <T extends ItemGroup> T register(String name, T ItemGroup) {
        return Registry.register(Registries.ITEM_GROUP, MoreToolsAndArmor.id(name), ItemGroup);
    }

    public static void load() {}
}
